<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Logout_ri-arrow-left-line</name>
   <tag></tag>
   <elementGuidId>b9027906-e8ad-4daf-a330-f5183f818490</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ri-arrow-left-line</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8b25de98-3efe-48e7-ae23-95dfaaac4f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-arrow-left-line</value>
      <webElementGuid>ee5e9833-a8e0-459f-891c-d38ca56ac70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;content&quot;]/nav[1]/div[@class=&quot;icon-container&quot;]/a[1]/i[@class=&quot;ri-arrow-left-line&quot;]</value>
      <webElementGuid>0a00a67b-da72-48a5-8596-b3d947a4db23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/i</value>
      <webElementGuid>f3c7bbd2-1375-4964-9c59-734272b377fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
