<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Konfirmasi</name>
   <tag></tag>
   <elementGuidId>21f7719c-5531-4f2e-9632-4ffce5db8021</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='order2']/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn-konfirmasi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#order2 >> internal:role=link[name=&quot;Konfirmasi&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a719a5e4-65f8-44fc-8bf3-a65cf5b854bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>konfirmasi_pesanan1.html?id=4</value>
      <webElementGuid>79519b40-eaff-4354-bb2d-97e9cdf1a4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-konfirmasi</value>
      <webElementGuid>a13d6e78-f0b1-4906-8007-4b03d493640c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Konfirmasi</value>
      <webElementGuid>4abbb6af-f8bb-4b50-891c-a17a739086c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order2&quot;)/a[@class=&quot;btn-konfirmasi&quot;]</value>
      <webElementGuid>3bb5611b-5d54-4175-85c7-471ec8399c7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='order2']/a[2]</value>
      <webElementGuid>8fd189b9-5821-48f6-8f19-3d02ae781e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Konfirmasi')]</value>
      <webElementGuid>28209aa1-cebd-468a-9a99-294681c55197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rincian Pesanan'])[2]/following::a[1]</value>
      <webElementGuid>b8b17fe4-2528-4bf9-8bec-61eb6aeb4644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::a[2]</value>
      <webElementGuid>9a9a3341-e721-4dba-b454-876cd28b59ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesanan 7'])[1]/preceding::a[1]</value>
      <webElementGuid>cb69fc5a-7d0d-49ae-8eb8-a4deab7b8e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waktu Pesanan'])[3]/preceding::a[1]</value>
      <webElementGuid>261c45e1-250f-46db-ba95-4af50c3354a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Konfirmasi']/parent::*</value>
      <webElementGuid>b8d69ac4-6a53-4606-8879-6c94037b0d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'konfirmasi_pesanan1.html?id=4')]</value>
      <webElementGuid>e792b089-6921-4435-846d-27e9df9a10bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>2925e17b-9189-442e-8386-4e11e6cd9cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'konfirmasi_pesanan1.html?id=4' and (text() = 'Konfirmasi' or . = 'Konfirmasi')]</value>
      <webElementGuid>2151bd89-8b1a-4f1d-a1df-b4af2d77c61c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
