<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Rincian Pesanan_1</name>
   <tag></tag>
   <elementGuidId>e6594cf6-c098-419f-9192-19573d96927b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='order2']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#order2 > a.btn-rincian</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#order2 >> internal:role=link[name=&quot;Rincian Pesanan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1e9c312f-7095-4198-84ac-f6bac77d137c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>rincian_pesanan1.html?id=4</value>
      <webElementGuid>88ce8768-17b8-40d9-b5db-e5a4f9dcc604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-rincian</value>
      <webElementGuid>fcd8b89d-69a6-4ead-8e83-57257ba9fcb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rincian Pesanan</value>
      <webElementGuid>626deaca-93dd-4ecb-afc8-c518ccb372b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order2&quot;)/a[@class=&quot;btn-rincian&quot;]</value>
      <webElementGuid>e63661e0-408f-4502-8c64-2b276aeb21ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='order2']/a</value>
      <webElementGuid>065a8dc4-2515-4945-afe8-6b7d801454aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Rincian Pesanan')])[2]</value>
      <webElementGuid>957e4bf8-65c7-4905-bf59-d4901c39bbb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::a[1]</value>
      <webElementGuid>7292a444-b872-4287-b226-655d5965e986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga Total'])[2]/following::a[1]</value>
      <webElementGuid>3d001465-24d6-46d6-8f88-e747835c7360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi'])[1]/preceding::a[1]</value>
      <webElementGuid>7ac4b68b-8365-4830-822a-8a2c1dffca1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesanan 7'])[1]/preceding::a[2]</value>
      <webElementGuid>be6fa94a-4650-49ef-a6c9-917aba22c602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'rincian_pesanan1.html?id=4')]</value>
      <webElementGuid>9d5a8613-2e8c-4859-b3fd-8bdfa505b458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>5558c016-c76c-4293-9240-74dc55a69018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'rincian_pesanan1.html?id=4' and (text() = 'Rincian Pesanan' or . = 'Rincian Pesanan')]</value>
      <webElementGuid>cb8eec44-6fc4-43f4-90fc-31e135c4b657</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
