<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Rincian Pesanan</name>
   <tag></tag>
   <elementGuidId>16151fa8-ae38-46cf-a5b1-794ba11bb38c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='order1']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn-rincian</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#order1 >> internal:role=link[name=&quot;Rincian Pesanan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>34062c9c-3f54-425b-87f3-41ce2af1bf45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>rincian_pesanan1.html?id=1</value>
      <webElementGuid>38c42f21-d608-481c-9efe-194422622ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-rincian</value>
      <webElementGuid>33a52cbb-b2fe-4bf8-827a-fb87444b508a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rincian Pesanan</value>
      <webElementGuid>263939d2-d5b7-44e1-a42d-942b73daef56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order1&quot;)/a[@class=&quot;btn-rincian&quot;]</value>
      <webElementGuid>dba2ce93-c490-438e-a994-6432403276ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='order1']/a</value>
      <webElementGuid>2f905235-7641-4a26-acc6-7593768c9421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Rincian Pesanan')]</value>
      <webElementGuid>168f95fd-2ca8-4686-ad83-077596ec2c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::a[1]</value>
      <webElementGuid>7ca0824f-a1bc-4433-9d5d-016fa19896a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga Total'])[1]/following::a[1]</value>
      <webElementGuid>a6e6cf09-d82e-40df-8e65-33d71e179586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesanan 4'])[1]/preceding::a[1]</value>
      <webElementGuid>4f230d44-a31e-46d1-bd71-b359eded3d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waktu Pesanan'])[2]/preceding::a[1]</value>
      <webElementGuid>f09113e5-fe0d-465b-ae37-01ae05b18d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rincian Pesanan']/parent::*</value>
      <webElementGuid>6c2128ed-ee12-49c9-8e1d-87fb17479c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'rincian_pesanan1.html?id=1')]</value>
      <webElementGuid>af4ae187-7116-4266-b69b-5ac1642edcc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>f88ce13e-4a21-452e-b154-ab887b7ee12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'rincian_pesanan1.html?id=1' and (text() = 'Rincian Pesanan' or . = 'Rincian Pesanan')]</value>
      <webElementGuid>bee805c8-a6e0-40b1-aff4-41377a3af464</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
