<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Logout_ri-arrow-left-line</name>
   <tag></tag>
   <elementGuidId>de4b7e0a-5b11-472a-9ff5-2dd35b5f53c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ri-arrow-left-line</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>db58608b-6c5a-4fa0-82eb-9eccc9bfdc77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-arrow-left-line</value>
      <webElementGuid>3c7c9f30-1912-475f-87bf-b7b369705219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;content&quot;]/nav[1]/div[@class=&quot;icon-container&quot;]/a[1]/i[@class=&quot;ri-arrow-left-line&quot;]</value>
      <webElementGuid>e520c507-9d5d-47dd-87ec-01c3e2d44fe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/i</value>
      <webElementGuid>e33d7105-ed9b-4f47-b0b8-196963d63a37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
