<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Logout_zoomable</name>
   <tag></tag>
   <elementGuidId>a4a3938c-f03d-417e-979a-9332e60b3df4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Image 1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.zoomable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Image 1&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>91b2d026-c899-465f-a5ae-b9193215b8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../img/priceList1.png</value>
      <webElementGuid>2dd8b003-3711-4386-96c8-864deee314fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Image 1</value>
      <webElementGuid>11666bd4-2ff4-4f5f-8118-3bb75bf12040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zoomable</value>
      <webElementGuid>f9ef9959-2dd4-469e-8e2d-af3e0a7aeeda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;content&quot;]/main[1]/div[@class=&quot;image-gallery&quot;]/div[1]/img[@class=&quot;zoomable&quot;]</value>
      <webElementGuid>144ead7b-3ce5-4981-9762-2e7848c3324c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Image 1']</value>
      <webElementGuid>297762a3-17ef-4186-ba91-66328ceac00b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
      <webElementGuid>7dfee64b-c9df-4224-a09e-c5d9db8aab10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../img/priceList1.png' and @alt = 'Image 1']</value>
      <webElementGuid>06fcf4c3-1477-4aef-aeea-29206290d6b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
