<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Logout_fas fa-calendar-check</name>
   <tag></tag>
   <elementGuidId>2dd523b4-812b-449b-a6a8-4ce5e641e7f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pesanan-baru']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-calendar-check</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#pesanan-baru i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2aa8ac4b-d175-4c69-bac1-81d2e095ec07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-calendar-check</value>
      <webElementGuid>6e381674-86b8-45d9-82fa-4f5593210f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pesanan-baru&quot;)/i[@class=&quot;fas fa-calendar-check&quot;]</value>
      <webElementGuid>5e541890-2d33-4c5b-97a9-7f30d065a387</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='pesanan-baru']/i</value>
      <webElementGuid>4fd5baad-b1bc-4f52-9acf-18a6f1d35f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/i</value>
      <webElementGuid>7931459e-ab3d-46ae-916a-0d6b69173dbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
