<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Logout_ri-arrow-left-line</name>
   <tag></tag>
   <elementGuidId>bba98e08-e960-4479-870a-6b691d192719</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ri-arrow-left-line</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>009af50f-47c3-4166-b56a-24431a935af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-arrow-left-line</value>
      <webElementGuid>3089f6d6-af75-438a-be44-4bcff7003aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;content&quot;]/nav[1]/div[@class=&quot;icon-container&quot;]/a[1]/i[@class=&quot;ri-arrow-left-line&quot;]</value>
      <webElementGuid>5ae1d797-18f3-4a31-afd4-996ef8dc37ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/i</value>
      <webElementGuid>03fb977d-1eef-43cf-a918-bddd3880492c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
